version: '3.8'

services:
  openchatbox:
    image: ghcr.io/frankdu1/openchatbox:main-a8e9dde
    container_name: openchatbox
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SCRIPT_NAME=/openchatbox
      - TZ=Asia/Shanghai
    volumes:
      - ./.env:/app/.env           # .env 在根目录
      - ./static:/app/static       # static 目录在根目录
    networks:
      - web-network

networks:
  web-network:
    driver: bridge